// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKPaKZ0aDD9XdOwIPhUnt69NeLs2rp-q4',
    appId: '1:28096104856:android:e30053fbfb1eaf334c03ed',
    messagingSenderId: '28096104856',
    projectId: 'flutter-fruity',
    storageBucket: 'flutter-fruity.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH4QgwC5uH8UUF5Rz0mrN4Y-xl3gxEtR8',
    appId: '1:28096104856:ios:ed574e269ec59fde4c03ed',
    messagingSenderId: '28096104856',
    projectId: 'flutter-fruity',
    storageBucket: 'flutter-fruity.appspot.com',
    androidClientId: '28096104856-ct6s4qok84vamq57clccbnj0l91bn61l.apps.googleusercontent.com',
    iosClientId: '28096104856-r2d6v01nus12ifg9i1bct38fecj8ugk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruity',
  );
}
