// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmCHoTGqlG4BofI0AAuG2gr8Kl9OQ9aq0',
    appId: '1:28096104856:web:51a29179ed16151e4c03ed',
    messagingSenderId: '28096104856',
    projectId: 'flutter-fruity',
    authDomain: 'flutter-fruity.firebaseapp.com',
    storageBucket: 'flutter-fruity.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKPaKZ0aDD9XdOwIPhUnt69NeLs2rp-q4',
    appId: '1:28096104856:android:e30053fbfb1eaf334c03ed',
    messagingSenderId: '28096104856',
    projectId: 'flutter-fruity',
    storageBucket: 'flutter-fruity.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbZ1ZHtXmiVmYXi_pUfXAo7azoCPy1DXc',
    appId: '1:28096104856:ios:d816c89777daf4194c03ed',
    messagingSenderId: '28096104856',
    projectId: 'flutter-fruity',
    storageBucket: 'flutter-fruity.appspot.com',
    androidClientId:
        '28096104856-ct6s4qok84vamq57clccbnj0l91bn61l.apps.googleusercontent.com',
    iosClientId:
        '28096104856-use1rea7p19g8139lfc7gqoc128qthqa.apps.googleusercontent.com',
    iosBundleId: 'com.fruity.app',
  );
}
